### ISSUE TITLE
setBacklight does not sync io device

### ISSUE THREAD

**Issue by kimble4** [davetcc/LiquidCrystal#9]
Using an LCD via a PCF8574 on i2c, with the usual arrangement of the backlight being driven by pin 3.  If you call setBacklight(), the change does not take effect until the next LCD command.

This appears to be due to the use of:
`ioDeviceDigitalWrite(_io_method, _backlightPin, state);`

...rather than the synchronised method.  This is a problem if you simply want to timeout (or illuminate) the backlight without changing the contents of the display.  I'm issuing a setCursor() after setting the backlight status as a work-around.

**Comment by davetcc** [comment]
Thanks for reporting, we'll get that fixed and released soon.

**Comment by davetcc** [comment]
Sorry it took a bit longer than usual, released today.
